### ISSUE TITLE
Disable strict mode in bodyParser.json

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-express#23]
https://github.com/digitalbazaar/bedrock-express/blob/master/lib/index.js#L136

http://expressjs.com/en/resources/middleware/body-parser.html#bodyparserjsonoptions

we want to add `strict: false` to the options there.

In addition, it is presently the case that when a failure occurs do to strict mode, the client is sent an internal server error and the error is swallowed by bedrock.  It is not displayed with --log-level debug.  This makes it very difficult to troubleshoot failures at this level in the stack.

**Comment by dlongley** [comment]
Addressed by #51.
