### ISSUE TITLE
Add code to handle configurations that use HTTP only

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-express#4]
This code needs to be added to projects that use HTTP only:

```js
// only run application on HTTP port
bedrock.events.on('bedrock-express.ready', function(app) {
  // attach express to regular http
  brServer.servers.http.on('request', app);
  // cancel default behavior of attaching to HTTPS
  return false;
});
```

It would be nice if we could make it so that this code will run automatically based on some configuration setting without people having to add it to their projects.

**Comment by mattcollier** [comment]
Config option for this landed https://github.com/digitalbazaar/bedrock-express/commit/e8f1d3d8c14be56823ebb06583f29b276325c2a4

Closing.
